app : 
  name : "go-pos"
  version : "1.0.0"
  author : "Aldi Syah Putra"

web : 
  port : 3000

log :
  level : 6

database : 
  username : "root"
  password : ""
  host : "localhost"
  port : 3306
  name : "pos"
  pool:
    idle: 10
    max: 100
    lifetime: 300